/**
 * Supported C++ type definitions within the execution engine.
 * Includes a string fallback to accommodate complex nested templates 
 * (e.g., "vector<int>") passed down by the Tree-Sitter AST.
 */
export type CppType = "int" | "double" | "bool" | "string" | "char" | "void" | "auto" | string;

/**
 * Represents the cross-compiled JavaScript equivalent of a C++ value in memory.
 * NOTE: `undefined` is used instead of `void` since `void` has no runtime value in JS.
 */
export type CppValue = 
  | number 
  | boolean 
  | string 
  | undefined
  | null 
  | CppValue[] 
  | Record<string, any> // Custom Structs, Classes, and proxy objects
  | Set<any>            // std::set & std::unordered_set polyfills
  | Map<any, any>       // std::map & std::unordered_map polyfills
  | ((...args: any[]) => any); // C++ Lambdas compiled to JS closures

/**
 * Execution milestones emitted during program execution.
 * Intercepted by the React UI to trigger synchronized animations and state updates.
 */
export enum EventType {
  DECLARE = "DECLARE",                 // Variable allocation
  /**
   * @deprecated Use ASSIGNMENT instead. Kept for backward compatibility with older
   * event consumers that may still listen on "ASSIGN".
   */
  ASSIGN = "ASSIGN",                   // Variable or index mutation (legacy)
  ASSIGNMENT = "ASSIGNMENT",           // Variable or index mutation (standard)
  READ = "READ",                       // Memory access/lookup
  WRITE = "WRITE",                     // Standard output stream (cout)
  CONDITION = "CONDITION",             // Branching logic evaluation
  LOOP_ENTER = "LOOP_ENTER",           // Initial loop block entry
  LOOP_ITERATION = "LOOP_ITERATION",   // Subsequent loop cycles
  LOOP_EXIT = "LOOP_EXIT",             // Loop termination
  FUNCTION_CALL = "FUNCTION_CALL",     // Frame pushed to Call Stack
  FUNCTION_RETURN = "FUNCTION_RETURN"  // Frame popped from Call Stack
}

/**
 * An isolated event payload generated by the engine during execution.
 */
export interface ExecutionEvent {
  id: string;                          // Unique UUID for React reconciliation
  step: number;                        // Chronological execution order
  line: number;                        // C++ source code line mapping
  type: EventType;                     // Action category
  payload: Record<string, unknown>;    // Contextual data (e.g., target variable, new value)
}

/**
 * The definitive, serialized execution state at a specific point in time.
 * Consumed by the React frontend to perfectly render the execution time-machine.
 */
export interface RuntimeSnapshot {
  step: number;
  line: number;
  event: {
    type: EventType;
    payload: Record<string, unknown>;
  };
  state: {
    // The frontend receives both the CppType and CppValue for rendering.
    variables: Record<string, { name: string; type: CppType; value: CppValue }>; 
    callStack: string[];                 
    scopeDepth: number;                  
  };
}